select * from zepto
limit 10

--1) What is the Total revenue generated by male vs female 
select "Gender",sum("Purchase_Amount") as revenue
from zepto 
group by "Gender"

--2) Which customers used discount but still spents more 
-- the average purchase amount
select "Customer_Id","Purchase_Amount"
from zepto
where "Discount_Applied" = 'Yes' and "Purchase_Amount" >= (
select avg("Purchase_Amount") from zepto)

--3) Which are the top 5 products with highest average review
select "Item_Purchased",round(avg("Review_Rating"::numeric),2)
as Avg_Product_Rating
from zepto
group by "Item_Purchased" order by avg("Review_Rating") desc
limit 5

--4) compare the average purchase amount between standard and express shipping
select "Shipping_Type",round(avg("Purchase_Amount"),2)
from zepto
where "Shipping_Type" in ('Standard','Express') 
group by "Shipping_Type"

--5) DO subscribed customers spent more ? compare average spend and total revenue
--spend by subscribers and non subscribers
select "Subscription_Status" ,
count("Customer_Id") as total_customers,
round(avg("Purchase_Amount"),2) as spent,
round(sum("Purchase_Amount"),2) as total_revenue
from zepto
group by "Subscription_Status"
order by "total_revenue","spent" desc

--6) which 5 products have the highest purchase with discount applied
select "Item_Purchased" ,
100 * sum(case when "Discount_Applied" = 'Yes' then 1 else 0 end)/ count(*)
as discount_rate
from zepto
group by "Item_Purchased" 
order by "discount_rate" desc
limit 5

/* segments customers into new returning and loyal based on
their total no of previous purchases and show the count of
each segment */
with "Customer_Type" as (
select "Customer_Id","Previous_Purchases",
case 
when "Previous_Purchases" = 1 then 'New'
when "Previous_Purchases" between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from zepto
)
select "customer_segment" , count(*) as "no_of_customers"
from "Customer_Type"
group by "customer_segment"

--8) what are the top 3 most purchase products within each category
with item_counts as(
select "Category","Item_Purchased",
count("Customer_Id") as total_orders,
row_number() over(partition by "Category" 
order by count("Customer_Id") desc)
as item_rank
from zepto
group by "Category","Item_Purchased"
)
select item_rank ,"Category","Item_Purchased",total_orders
from item_counts
where item_rank <=3

--9) are customers who are repeat buyers more than 5 previous purchases also likely to subscribe
select "Subscription_Status",
count("Customer_Id") as repeat_buyers
from zepto
where "Previous_Purchases" > 5
group by "Subscription_Status"

--10) what is the revenue contributed by each group
select "age_group" , sum("Purchase_Amount") as total_revenue
from zepto
group by "age_group"
order by total_revenue desc


